import type { CardCategory } from "@mtg/core/contract";

/** A color identity key: the five colors plus colorless. */
export type ColorKey = "W" | "U" | "B" | "R" | "G" | "C";

export interface FeaturedDeck {
  slug: string;
  commanderName: string;
  summary: string;
  decklist: string;
  composition: Record<CardCategory, number>;
  /** Deck cards counted under every color in their identity; empty identity (incl. basics) is C. */
  colorCounts: Record<ColorKey, number>;
  cardCount: number;
}

/**
 * The featured decks on the landing page: the most-built commanders in our own corpus, each built from
 * aggregate play rates rather than any one player's deck (top nonlands by inclusion, most-played
 * nonbasic lands, basics to 100). Generated by scripts/build-featured-decks.ts — do not hand-edit.
 */
export const FEATURED_DECKS: readonly FeaturedDeck[] = [
  {
    slug: "the-ur-dragon",
    commanderName: "The Ur-Dragon",
    summary:
      "The Ur-Dragon decks are built around cost reducer creature, draw engine and land ramp.",
    decklist: `Commander
1 The Ur-Dragon

Deck
1 Sol Ring
1 Miirym, Sentinel Wyrm
1 Dragon Tempest
1 Arcane Signet
1 Temur Ascendancy
1 Tiamat
1 Terror of the Peaks
1 Crux of Fate
1 Dragonlord Dromoka
1 Hellkite Courser
1 Old Gnawbone
1 Farseek
1 Goldspan Dragon
1 Atarka, World Render
1 Ancient Copper Dragon
1 Sarkhan, Soul Aflame
1 Lathliss, Dragon Queen
1 Nature's Lore
1 Ureni of the Unwritten
1 Klauth, Unrivaled Ancient
1 Scourge of Valkas
1 Utvara Hellkite
1 Morophon, the Boundless
1 Rhythm of the Wild
1 Urza's Incubator
1 Three Visits
1 Heroic Intervention
1 Garruk's Uprising
1 Swords to Plowshares
1 Birds of Paradise
1 Rivaz of the Claw
1 Dragon's Hoard
1 Ancient Silver Dragon
1 Ancient Gold Dragon
1 Rith, Liberated Primeval
1 Dragonspeaker Shaman
1 Twinflame Tyrant
1 Dracogenesis
1 Roaming Throne
1 Balefire Dragon
1 Cyclonic Rift
1 Smothering Tithe
1 Chromatic Lantern
1 Two-Headed Hellkite
1 Scion of Draco
1 Scion of the Ur-Dragon
1 Bloom Tender
1 Dragonlord's Servant
1 Teferi's Protection
1 Call the Spirit Dragons
1 Scalelord Reckoner
1 Mox Jasper
1 Herald's Horn
1 Bladewing the Risen
1 Lightning Greaves
1 Rhystic Study
1 Silumgar, the Drifting Death
1 Cultivate
1 Fellwar Stone
1 Ramos, Dragon Engine
1 The Great Henge
1 Demonic Tutor
1 Ganax, Astral Hunter
1 Command Tower
1 Stomping Ground
1 Haven of the Spirit Dragon
1 Cavern of Souls
1 Overgrown Tomb
1 Exotic Orchard
1 Breeding Pool
1 Path of Ancestry
1 Temple Garden
1 Blood Crypt
1 Steam Vents
1 Ketria Triome
1 Sacred Foundry
1 Maelstrom of the Spirit Dragon
1 Wooded Foothills
1 Arid Mesa
1 Windswept Heath
1 Misty Rainforest
1 Bloodstained Mire
1 Verdant Catacombs
1 Scalding Tarn
1 Watery Grave
1 Hallowed Fountain
1 Godless Shrine
3 Plains
3 Island
2 Swamp
2 Mountain
2 Forest`,
    composition: {
      creature: 36,
      instant: 4,
      sorcery: 6,
      artifact: 10,
      enchantment: 8,
      planeswalker: 0,
      battle: 0,
      land: 36,
    },
    colorCounts: {
      W: 18,
      U: 20,
      B: 16,
      R: 36,
      G: 30,
      C: 36,
    },
    cardCount: 100,
  },
  {
    slug: "miirym-sentinel-wyrm",
    commanderName: "Miirym, Sentinel Wyrm",
    summary:
      "Miirym, Sentinel Wyrm decks are built around copy creature, copy legendary and repeatable creature tokens.",
    decklist: `Commander
1 Miirym, Sentinel Wyrm

Deck
1 Sol Ring
1 Arcane Signet
1 Dragon Tempest
1 Ganax, Astral Hunter
1 Temur Ascendancy
1 Scourge of Valkas
1 Terror of the Peaks
1 Garruk's Uprising
1 Dragonspeaker Shaman
1 Ureni of the Unwritten
1 Lathliss, Dragon Queen
1 Wrathful Red Dragon
1 Farseek
1 Old Gnawbone
1 Goldspan Dragon
1 Nature's Lore
1 Roaming Throne
1 Atarka, World Render
1 Klauth, Unrivaled Ancient
1 Sarkhan, Soul Aflame
1 Dragon's Hoard
1 Astral Dragon
1 Heroic Intervention
1 Dragonborn Champion
1 Dragonlord's Servant
1 Ancient Silver Dragon
1 Counterspell
1 Scaled Nurturer
1 Ancient Copper Dragon
1 Cultivate
1 Beast Within
1 Thrakkus the Butcher
1 Utvara Hellkite
1 Blasphemous Act
1 Kodama's Reach
1 Twinflame Tyrant
1 Panharmonicon
1 Rhythm of the Wild
1 Three Visits
1 Earthquake Dragon
1 Urza's Incubator
1 Savage Ventmaw
1 Balefire Dragon
1 Korlessa, Scale Singer
1 Kindred Discovery
1 Birds of Paradise
1 Temur Battlecrier
1 Elemental Bond
1 Cyclonic Rift
1 Lightning Greaves
1 Lozhan, Dragons' Legacy
1 Drakuseth, Maw of Flames
1 Carnelian Orb of Dragonkind
1 Rampant Growth
1 Herald's Horn
1 Dracogenesis
1 Spark Double
1 Chaos Warp
1 Rhystic Study
1 Jade Orb of Dragonkind
1 Parallel Lives
1 Mox Jasper
1 Dragonhawk, Fate's Tempest
1 Command Tower
1 Haven of the Spirit Dragon
1 Stomping Ground
1 Breeding Pool
1 Steam Vents
1 Path of Ancestry
1 Ketria Triome
1 Maelstrom of the Spirit Dragon
1 Exotic Orchard
1 Frontier Bivouac
1 Spire Garden
1 Training Center
1 Rockfall Vale
1 Rejuvenating Springs
1 Cinder Glade
1 Cavern of Souls
1 Wooded Foothills
1 Sulfur Falls
1 Shivan Reef
1 Misty Rainforest
1 Scalding Tarn
1 Rootbound Crag
1 Hinterland Harbor
1 Temple of the Dragon Queen
4 Island
4 Mountain
4 Forest`,
    composition: {
      creature: 33,
      instant: 5,
      sorcery: 7,
      artifact: 10,
      enchantment: 9,
      planeswalker: 0,
      battle: 0,
      land: 36,
    },
    colorCounts: {
      W: 0,
      U: 23,
      B: 0,
      R: 42,
      G: 37,
      C: 31,
    },
    cardCount: 100,
  },
  {
    slug: "atraxa-praetors-voice",
    commanderName: "Atraxa, Praetors' Voice",
    summary:
      "Atraxa, Praetors' Voice decks are built around repeatable lifegain, repeatable proliferate and evasion.",
    decklist: `Commander
1 Atraxa, Praetors' Voice

Deck
1 Sol Ring
1 Arcane Signet
1 Tekuthal, Inquiry Dominus
1 Vraska, Betrayal's Sting
1 Swords to Plowshares
1 Astral Cornucopia
1 Ezuri, Stalker of Spheres
1 Evolution Sage
1 Vorinclex, Monstrous Raider
1 Tezzeret's Gambit
1 Farseek
1 Chromatic Lantern
1 Inexorable Tide
1 Prologue to Phyresis
1 Everflowing Chalice
1 Thrummingbird
1 Infectious Inquiry
1 Rhystic Study
1 Cyclonic Rift
1 Doubling Season
1 Vraska's Fall
1 Nature's Lore
1 Skrelv, Defector Mite
1 Flux Channeler
1 Phyresis Outbreak
1 Brokers Ascendancy
1 Bloated Contaminator
1 Deepglow Skate
1 Teferi's Protection
1 Birds of Paradise
1 Path to Exile
1 Ichor Rats
1 Dreamtide Whale
1 Cultivate
1 Tamiyo, Field Researcher
1 Experimental Augury
1 Infectious Bite
1 Venerated Rotpriest
1 Glistening Sphere
1 Staff of Compleation
1 Counterspell
1 Demonic Tutor
1 Unnatural Restoration
1 Smothering Tithe
1 Innkeeper's Talent
1 Cankerbloom
1 Ajani, Sleeper Agent
1 Blighted Agent
1 Norn's Decree
1 Contaminant Grafter
1 Three Visits
1 Contagion Engine
1 Ixhel, Scion of Atraxa
1 Fellwar Stone
1 Heroic Intervention
1 Sword of Truth and Justice
1 Farewell
1 Vampiric Tutor
1 Skithiryx, the Blight Dragon
1 Lightning Greaves
1 Mana Drain
1 Assassin's Trophy
1 Anguished Unmaking
1 Command Tower
1 Exotic Orchard
1 Hallowed Fountain
1 Breeding Pool
1 Karn's Bastion
1 Overgrown Tomb
1 Godless Shrine
1 Temple Garden
1 Watery Grave
1 Windswept Heath
1 Polluted Delta
1 Spara's Headquarters
1 Verdant Catacombs
1 Flooded Strand
1 Zagoth Triome
1 Indatha Triome
1 Marsh Flats
1 Misty Rainforest
1 Raffine's Tower
1 Seaside Citadel
1 Sandsteppe Citadel
1 Arcane Sanctum
1 City of Brass
1 Undergrowth Stadium
3 Plains
3 Island
3 Swamp
3 Forest`,
    composition: {
      creature: 19,
      instant: 14,
      sorcery: 10,
      artifact: 11,
      enchantment: 7,
      planeswalker: 3,
      battle: 0,
      land: 36,
    },
    colorCounts: {
      W: 22,
      U: 26,
      B: 21,
      R: 0,
      G: 32,
      C: 33,
    },
    cardCount: 100,
  },
] as const;
